// <auto-generated />
using System;
using API.Web.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428223607_SeedDataUpdated")]
    partial class SeedDataUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("API.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 1, 10, 10, 10, 0, DateTimeKind.Unspecified),
                            Email = "alice@example.com",
                            Name = "Alice Johnson",
                            Phone = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 1, 10, 10, 10, 0, DateTimeKind.Unspecified),
                            Email = "bob@example.com",
                            Name = "Bob Smith",
                            Phone = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 4, 1, 10, 10, 10, 0, DateTimeKind.Unspecified),
                            Email = "carol@example.com",
                            Name = "Carol White",
                            Phone = "555-0103"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 4, 1, 10, 10, 10, 0, DateTimeKind.Unspecified),
                            Email = "david@example.com",
                            Name = "David Brown",
                            Phone = "555-0104"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 4, 1, 10, 10, 10, 0, DateTimeKind.Unspecified),
                            Email = "eva@example.com",
                            Name = "Eva Martinez",
                            Phone = "555-0105"
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            QuantityAvailable = 20,
                            UpdatedAtUtc = new DateTime(2026, 2, 28, 10, 10, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            QuantityAvailable = 100,
                            UpdatedAtUtc = new DateTime(2026, 2, 28, 10, 10, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            QuantityAvailable = 50,
                            UpdatedAtUtc = new DateTime(2026, 2, 28, 10, 10, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            QuantityAvailable = 15,
                            UpdatedAtUtc = new DateTime(2026, 2, 28, 10, 10, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            QuantityAvailable = 75,
                            UpdatedAtUtc = new DateTime(2026, 2, 28, 10, 10, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            QuantityAvailable = 40,
                            UpdatedAtUtc = new DateTime(2026, 2, 28, 10, 10, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            QuantityAvailable = 30,
                            UpdatedAtUtc = new DateTime(2026, 2, 28, 10, 10, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            QuantityAvailable = 60,
                            UpdatedAtUtc = new DateTime(2026, 2, 28, 10, 10, 10, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("API.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("API.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptop",
                            Name = "Laptop Pro 15",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "RGB mechanical keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "27-inch 4K display",
                            Name = "4K Monitor",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "7-in-1 USB-C hub",
                            Name = "USB-C Hub",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "1080p webcam",
                            Name = "Webcam HD",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "ANC headphones",
                            Name = "Noise Cancelling Headphones",
                            Price = 349.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "NVMe SSD",
                            Name = "SSD 1TB",
                            Price = 119.99m
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("API.Domain.Entities.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("API.Domain.Entities.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Domain.Entities.Order", b =>
                {
                    b.HasOne("API.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("API.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("API.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("API.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("API.Domain.Entities.Product", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
